---
- name: Install gcc
  become: true
  ansible.builtin.package:
    name: "gcc"
    state: "present"

- name: Create a .c file named {{ ipmi_exporter_fakeroot_filename }}
  ansible.builtin.copy:
    content: "int getuid() { return 0; }"
    dest: "/tmp/{{ ipmi_exporter_fakeroot_filename }}.c"

- name: Ensure existence of directory {{ ipmi_exporter_fakeroot_path }}
  ansible.builtin.file:
    path: "{{ ipmi_exporter_fakeroot_path }}"
    state: "directory"
    mode: "0750"
    owner: "{{ ipmi_exporter_system_user }}"
    group: "{{ ipmi_exporter_system_group }}"

- name: Build a .so file named {{ ipmi_exporter_fakeroot_filename }}
  ansible.builtin.command:
    cmd: >
      gcc /tmp/{{ ipmi_exporter_fakeroot_filename }}.c -nostdlib -shared -O2 -o
      {{ ipmi_exporter_fakeroot_path }}/{{ ipmi_exporter_fakeroot_filename }}.so

- name: Set permissions for .so file
  ansible.builtin.file:
    path: "{{ ipmi_exporter_fakeroot_path }}/{{ ipmi_exporter_fakeroot_filename }}.so"
    state: "file"
    mode: "0440"
    owner: "{{ ipmi_exporter_system_user }}"
    group: "{{ ipmi_exporter_system_group }}"
  when: "not {{ ansible_check_mode }}"
